### ISSUE TITLE
Links to specific methods in the docs hide the method under the header bar

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#637]
Looks like when you reference a specific method, the anchor ends up getting hidden under the blue header bar. It'd be really nice if we could find a way to make the method visible (and maybe highlight it?)

See http://googlecloudplatform.github.io/gcloud-python/storage-blobs.html#gcloud.storage.blob.Blob.rename (notice "rename" isn't visible until you scroll up a bit).

**Comment by dhermes** [comment]
I agree :+1: I wish I would have filed this weeks ago.

**Comment by tseaver** [comment]
I think we're being hosed by the z-order of the Big Blue Bar:  I don't know how to get the browser to do differently.

**Comment by jgeewax** [comment]
I think we just need to make the anchor link position be a bit offset. (ie, http://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header)

**Comment by blowmage** [comment]
Adding the following to `main.css` helps tremendously:

```css
*[id]:before,
a[name]:before {
  display: block;
  content: " ";
  margin-top: -80px;
  height: 80px;
  visibility: hidden;
}
```
