### ISSUE TITLE
Cannot combine 'order' and 'filters' in same query 

### ISSUE THREAD

**Issue by thesandlord** [GoogleCloudPlatform/gcloud-python#860]
I am trying to query comments that belong to a story.

```python
query = datastore.Query(kind='Comment', filters=[('storyid', '=', 12345)], order=['timestamp'])
```

This code breaks with to following error (I also have additional internal debug info I can share):
```python
gcloud.exceptions.PreconditionFailed: 412 no matching index found.
```

Trying to debug this, I found the following work with no problems:

Removing order
```python
query = datastore.Query(kind='Comment', filters=[('storyid', '=', 12345)])
```

Removing filters
```python
query = datastore.Query(kind='Comment', order=['timestamp'])
```

Changing order to use storyid
```python
query = datastore.Query(kind='Comment', filters=[('storyid', '=', 12345)], order=['storyid'])
```

Why is this happening? The fact that the bottom three queries work and to top one does not is very confusing. Nothing I saw in the documentation indicates that filters and order affect each other.

**Comment by dhermes** [comment]
/cc @pcostell Maybe the error could list which index is required?

@thesandlord Give me a moment, I'll tell you which index is required (and how I determined that).

**Comment by dhermes** [comment]
@thesandlord I fired up the App Engine [dev server][1] and executed

```python
from google.appengine.ext import ndb


class Comment(ndb.Model):
    story_id = ndb.IntegerProperty()
    timestamp = ndb.DateTimeProperty()


q = Comment.query(Comment.story_id == 12345).order(Comment.timestamp)
print q.fetch()
```

from the [Interactive Console][2].

After doing this, the dev server autogenerated the following `index.yaml` file:

```yaml
indexes:

# AUTOGENERATED

# This index.yaml is automatically updated whenever the dev_appserver
# detects that a new type of query is run.  If you want to manage the
# index.yaml file manually, remove the above marker line (the line
# saying "# AUTOGENERATED").  If you want to manage some indexes
# manually, move them above the marker line.  The index.yaml file is
# automatically uploaded to the admin console when you next deploy
# your application using appcfg.py.

- kind: Comment
  properties:
  - name: story_id
  - name: timestamp
```

[1]: https://cloud.google.com/appengine/docs/python/tools/devserver
[2]: https://cloud.google.com/appengine/docs/python/tools/devserver#Python_The_Interactive_Console
